### ISSUE TITLE
Atmosphere version 0.0.31 causes error when testing with Velocity

### ISSUE THREAD

**Issue by spencern** [CollectionFS/Meteor-http-methods#52]
When running package tests with Velocity (`VELOCITY_TEST_PACKAGES=1 meteor test-packages --driver-package velocity:html-reporter --port 5000`) we're seeing this error in v0.0.31 as published on Atmosphere.

```
$>  .meteor/packages/meteor-tool/.1.1.10.1metfpd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
$>                          throw(ex);
$>                                ^
$>  Error: HTTP.methods not implemented on client-side
$>      at Object.HTTP.methods (/private/var/folders/v9/txwznh8d5fg8bgz0fw0f9s080000gn/T/meteor-test-runwsg69e/.meteor/local/build/programs/server/packages/cfs_http-methods.js:688:9)
$>      at Package (/private/var/folders/v9/txwznh8d5fg8bgz0fw0f9s080000gn/T/meteor-test-runwsg69e/.meteor/local/build/programs/server/packages/cfs_access-point.js:861:6)
$>      at Package (/private/var/folders/v9/txwznh8d5fg8bgz0fw0f9s080000gn/T/meteor-test-runwsg69e/.meteor/local/build/programs/server/packages/cfs_access-point.js:881:4)
$>      at /private/var/folders/v9/txwznh8d5fg8bgz0fw0f9s080000gn/T/meteor-test-runwsg69e/.meteor/local/build/programs/server/packages/cfs_access-point.js:885:4
$>      at /private/var/folders/v9/txwznh8d5fg8bgz0fw0f9s080000gn/T/meteor-test-runwsg69e/.meteor/local/build/programs/server/packages/cfs_access-point.js:892:3
$>      at /private/var/folders/v9/txwznh8d5fg8bgz0fw0f9s080000gn/T/meteor-test-runwsg69e/.meteor/local/build/programs/server/boot.js:242:10
$>      at Array.forEach (native)
$>      at Function._.each._.forEach (.meteor/packages/meteor-tool/.1.1.10.1metfpd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
$>      at /private/var/folders/v9/txwznh8d5fg8bgz0fw0f9s080000gn/T/meteor-test-runwsg69e/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
```

cloning the latest master (`v0.0.30`) from github into our `/packages` directory solves the issue.

It appears that `v0.0.31` was never published to github either and so I can't speculate as to the cause of the issue.

@aaronjudd and the @reactioncommerce team are experiencing the issue as well.

**Comment by raix** [comment]
@spencern I've just pushed to git - let me know if that solves the issue

**Comment by sebakerckhof** [comment]
Got the same error even without running tests. Just running my meteor project gives me this error.

**Comment by sebakerckhof** [comment]
Cloning the repo doesn't give me this error. It seems the version published to atmosphere is faulty. If I look at the directory of the cached package from atmosphere, it appears the client file is present on the server and vice-versa:

![image](https://cloud.githubusercontent.com/assets/88471/14351444/9b9a84d2-fccf-11e5-8ab9-e64ab7b6de82.png)

**Comment by aaronjudd** [comment]
@raix I can verify that the problem still exists.

**Comment by spencern** [comment]
@raix The problem still exists for me when using the atmosphere version. I can still clone the latest from github (`v0.0.31`) and it works fine.

I concur with @sebakerckhof that it seems like an issue with the package on atmosphere.

**Comment by raix** [comment]
odd - I can try and publish a new version

**Comment by sebakerckhof** [comment]
@raix Which version of Meteor tool do you use? I vaguely remember an issue on this in one of the meteor 1.3 beta releases.

**Comment by raix** [comment]
Ive reinstalled meteor (was running slow anyway) and bumped the version. Let me know if its fixed

**Comment by spencern** [comment]
It's working for me. @aaronjudd @sebakerckhof want to confirm?

**Comment by aaronjudd** [comment]
:+1: I can confirm this is resolved.

**Comment by sebakerckhof** [comment]
Same. thanks.

**Comment by raix** [comment]
thanks guys
